### ISSUE TITLE
Unable to receive data from S3 source to Redis Broker

### ISSUE THREAD

**Issue by jewel-mascarenhas** [triggermesh/brokers#146]
I'm currently validating a basic use case of capturing events in Redis for S3 File Upload Event using a Triggermesh managed Redis Broker (`redisbroker.yml`). I'm able to receive those events in the SQS queue that is created as part of the `s3source.yml`

However, when I interact with the Redis Server using redis-cli, I'm unable to see any data being stored.
Can anyone please suggest if I'm missing out on any configurations?

```
kubectl exec -ti myredis-rb-redis-xxx -- redis-cli       
127.0.0.1:6379> keys *
(empty array)
127.0.0.1:6379> scan 0
1) "0"
2) (empty array)
```

```
kubectl get pods
NAME                                  READY   STATUS    RESTARTS   AGE
awss3source-s3data-xxx   1/1     Running   0          27m
knative-operator-xxx      1/1     Running   0          33m
myredis-rb-broker-xxx     1/1     Running   0          29m
myredis-rb-redis-xxx     1/1     Running   0          29m
operator-webhook-xxx     1/1     Running   0          33m
```
```
# redisbroker.yml
apiVersion: eventing.triggermesh.io/v1alpha1
kind: RedisBroker
metadata:
  name: myredis
```

```
# s3source.yml
apiVersion: sources.triggermesh.io/v1alpha1
kind: AWSS3Source
metadata:
  name: s3data
spec:
  arn: arn:aws:s3:::mytmsrc

  eventTypes:
  - s3:ObjectCreated:*

  auth:
    credentials:
      accessKeyID:
        valueFromSecret:
          name: aws
          key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        valueFromSecret:
          name: aws
          key: AWS_SECRET_ACCESS_KEY

  sink:
    ref:
      apiVersion: eventing.triggermesh.io/v1alpha1
      kind: RedisBroker
      name: myredis
```

**Comment by odacremolbap** [comment]
Hi @jewel-mascarenhas ,

data is stored temporarily as Redis streams. You can try the `XINFO STREAMS` and X-prefixed commands.

**Comment by jewel-mascarenhas** [comment]
Hello Pablo,

Thanks for your quick response.

I did try the X-commands onto the redis instance but the results were not satisfactory

```
kubectl exec -ti myredis-rb-redis-xxx -- redis-cli 
127.0.0.1:6379>  scan 0
1) "0"
2) 1) "default.myredis"
127.0.0.1:6379> xinfo groups default.myredis
(empty array)
127.0.0.1:6379> xinfo consumers default.myredis default
(error) NOGROUP No such consumer group 'default' for key name 'default.myredis'
```

Even so, I have tried to deploy the remaining parts such as Trigger, Target and Service (sockeye) to view the events. 
Unfortunately, I've not been able to view any events onto Sockeye either.
Could you please help me understand if I am missing something here?

Their manifests can be found below 
```
# trigger.yml
apiVersion: eventing.triggermesh.io/v1alpha1
kind: Trigger
metadata:
  name: s3trigger
spec:
  broker:
    kind: RedisBroker
    group: eventing.triggermesh.io
    name: myredis
  target:
    ref:
       apiVersion: v1alpha1
       kind: CloudEventsTarget
       name: mytarget
```

```
# target.yml
apiVersion: targets.triggermesh.io/v1alpha1
kind: CloudEventsTarget
metadata:
  name: mytarget
spec:
  endpoint: http://sock.default.x.x.x.x.sslip.io
```

```
# sockeye.yml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sock
spec:
  template:
    spec:
      containers:
        - image: docker.io/n3wscott/sockeye:v0.7.0@sha256:e603d8494eeacce966e57f8f508e4c4f6bebc71d095e3f5a0a1abaf42c5f0e48
```

![image](https://user-images.githubusercontent.com/115950176/232334264-998b11ae-faf5-40a0-9464-5215948e92d5.png)
