### ISSUE TITLE
Handle URI in triggers

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/brokers#166]
Knative triggers support uri for subscription, we should too:

```
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: my-service-trigger
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: my-service
    uri: /my-custom-path
```
